version: "3.8"

services:
  frontend:
    build: ./client
    image: pradeep079/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: .
    image: pradeep079/backend:latest
    ports:
      - "5000:5000"
    
    # env_file:
    #   - .env
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://pradeep:Travel123@e-commerce.05vrejg.mongodb.net/Alumni-app?retryWrites=true&w=majority
      - NODE_ENV=production
      - JWT_SECRET=mysecret123
      - NODE_ENV=production
      - SENDER_EMAIL=pradeepk9348@gmail.com
      - BREVO_EMAIL=pradeepk9348@gmail.com
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"